server:
  port: 8181
#激活dev环境
spring:
  profiles:
    active: prod
---
spring:
  profiles: prod
#redis:
#  config:
#    address: 127.0.0.1
#    port: 6379
##开启springboot的debug 可以查看自动配置报告，用来判断哪些自动配置生效
##debug: true
#
#日志级别 将com.zdj包下的日志级别设置为trace
logging:
  level:
    com.zdj: trace
  # 当前磁盘根目录下创建springboot文件夹和log子文件夹，使用spring.log作为默认文件
  path: /springboot/log/
white: yui

##日志保存在当前磁盘下spring文件夹下的spring.log文件   path是指定目录  file是指定文件  也可以指定日志格式
#logging:
#  path: /spring
server:
  port: 8888

---
spring:
  profiles: uat
server:
  port: 8999
